data_url = "https://stats.nba.com/stats/leaguedashteamstats?Conference=&DateFrom=&DateTo=&Division=&GameScope=&GameSegment=&Height=&ISTRound=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=PerGame&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season=2024-25&SeasonSegment=&SeasonType=Playoffs&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision="

[get-data]
    [get-data.2007-08]
        start_date = "2007-09-29"
        end_date   = "2008-06-04"
        start_year = "2007"
        end_year   = "2008"

    [get-data.2008-09]
        start_date = "2008-10-04"
        end_date   = "2009-06-12"
        start_year = "2008"
        end_year   = "2009"

    [get-data.2009-10]
        start_date = "2009-10-01"
        end_date   = "2010-06-09"
        start_year = "2009"
        end_year   = "2010"

    [get-data.2010-11]
        start_date = "2010-10-07"
        end_date   = "2011-06-15"
        start_year = "2010"
        end_year   = "2011"

    [get-data.2011-12]
        start_date = "2011-10-06"
        end_date   = "2012-06-11"
        start_year = "2011"
        end_year   = "2012"

    [get-data.2012-13]  
        start_date = "2013-01-19"
        end_date   = "2013-06-24"
        start_year = "2012"
        end_year   = "2013"

    [get-data.2013-14]
        start_date = "2013-10-01"
        end_date   = "2014-06-13"
        start_year = "2013"
        end_year   = "2014"

    [get-data.2014-15]
        start_date = "2014-10-08"
        end_date   = "2015-06-15"
        start_year = "2014"
        end_year   = "2015"

    [get-data.2015-16]
        start_date = "2015-10-07"
        end_date   = "2016-06-12"
        start_year = "2015"
        end_year   = "2016"

    [get-data.2016-17]
        start_date = "2016-10-12"
        end_date   = "2017-06-11"
        start_year = "2016"
        end_year   = "2017"

    [get-data.2017-18]
        start_date = "2017-10-04"
        end_date   = "2018-06-07"
        start_year = "2017"
        end_year   = "2018"

    [get-data.2018-19]
        start_date = "2018-10-03"
        end_date   = "2019-06-12"
        start_year = "2018"
        end_year   = "2019"

    [get-data.2019-20]   
        start_date = "2019-10-02"
        end_date   = "2020-09-28"
        start_year = "2019"
        end_year   = "2020"

    [get-data.2020-21]   
        start_date = "2021-01-13"
        end_date   = "2021-07-07"
        start_year = "2020"
        end_year   = "2021"

    [get-data.2021-22]
        start_date = "2021-10-12"
        end_date   = "2022-06-26"
        start_year = "2021"
        end_year   = "2022"

    [get-data.2022-23]
        start_date = "2022-10-07"
        end_date   = "2023-06-13"
        start_year = "2022"
        end_year   = "2023"

    [get-data.2023-24]
        start_date = "2023-10-10"
        end_date   = "2024-06-24"
        start_year = "2023"
        end_year   = "2024"

    [get-data.2024-25]
        start_date = "2024-10-04"
        end_date   = "2025-06-17"
        start_year = "2024"
        end_year   = "2025"


[get-odds-data]
    [get-odds-data.2009-10]
        start_date = "2009-10-01"
        end_date   = "2010-06-09"
        start_year = "2009"
        end_year   = "2010"

    [get-odds-data.2010-11]
        start_date = "2010-10-07"
        end_date   = "2011-06-15"
        start_year = "2010"
        end_year   = "2011"

    [get-odds-data.2011-12]
        start_date = "2011-10-06"
        end_date   = "2012-06-11"
        start_year = "2011"
        end_year   = "2012"

    [get-odds-data.2012-13]  
        start_date = "2013-01-19"
        end_date   = "2013-06-24"
        start_year = "2012"
        end_year   = "2013"

    [get-odds-data.2013-14]
        start_date = "2013-10-01"
        end_date   = "2014-06-13"
        start_year = "2013"
        end_year   = "2014"

    [get-odds-data.2014-15]
        start_date = "2014-10-08"
        end_date   = "2015-06-15"
        start_year = "2014"
        end_year   = "2015"

    [get-odds-data.2015-16]
        start_date = "2015-10-07"
        end_date   = "2016-06-12"
        start_year = "2015"
        end_year   = "2016"

    [get-odds-data.2016-17]
        start_date = "2016-10-12"
        end_date   = "2017-06-11"
        start_year = "2016"
        end_year   = "2017"

    [get-odds-data.2017-18]
        start_date = "2017-10-04"
        end_date   = "2018-06-07"
        start_year = "2017"
        end_year   = "2018"

    [get-odds-data.2018-19]
        start_date = "2018-10-03"
        end_date   = "2019-06-12"
        start_year = "2018"
        end_year   = "2019"

    [get-odds-data.2019-20]   
        start_date = "2019-10-02"
        end_date   = "2020-09-28"
        start_year = "2019"
        end_year   = "2020"

    [get-odds-data.2020-21]   
        start_date = "2021-01-13"
        end_date   = "2021-07-07"
        start_year = "2020"
        end_year   = "2021"

    [get-odds-data.2021-22]
        start_date = "2021-10-12"
        end_date   = "2022-06-26"
        start_year = "2021"
        end_year   = "2022"

[create-games]
    [create-games.2009-10]
        start_date = "2009-10-01"
        end_date   = "2010-06-09"
        start_year = "2009"
        end_year   = "2010"

    [create-games.2010-11]
        start_date = "2010-10-07"
        end_date   = "2011-06-15"
        start_year = "2010"
        end_year   = "2011"

    [create-games.2011-12]
        start_date = "2011-10-06"
        end_date   = "2012-06-11"
        start_year = "2011"
        end_year   = "2012"

    [create-games.2012-13]  
        start_date = "2013-01-19"
        end_date   = "2013-06-24"
        start_year = "2012"
        end_year   = "2013"

    [create-games.2013-14]
        start_date = "2013-10-01"
        end_date   = "2014-06-13"
        start_year = "2013"
        end_year   = "2014"

    [create-games.2014-15]
        start_date = "2014-10-08"
        end_date   = "2015-06-15"
        start_year = "2014"
        end_year   = "2015"

    [create-games.2015-16]
        start_date = "2015-10-07"
        end_date   = "2016-06-12"
        start_year = "2015"
        end_year   = "2016"

    [create-games.2016-17]
        start_date = "2016-10-12"
        end_date   = "2017-06-11"
        start_year = "2016"
        end_year   = "2017"

    [create-games.2017-18]
        start_date = "2017-10-04"
        end_date   = "2018-06-07"
        start_year = "2017"
        end_year   = "2018"

    [create-games.2018-19]
        start_date = "2018-10-03"
        end_date   = "2019-06-12"
        start_year = "2018"
        end_year   = "2019"

    [create-games.2019-20]   
        start_date = "2019-10-02"
        end_date   = "2020-09-28"
        start_year = "2019"
        end_year   = "2020"

    [create-games.2020-21]   
        start_date = "2021-01-13"
        end_date   = "2021-07-07"
        start_year = "2020"
        end_year   = "2021"

    [create-games.2021-22]
        start_date = "2021-10-12"
        end_date   = "2022-06-26"
        start_year = "2021"
        end_year   = "2022"